# Generated by Django 2.2.16 on 2021-08-23 14:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0002_post_group'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='follow',
            name='unique_list',
        ),
    ]
